services:
  guardepi:
    build:
      context: .
    image: guardepi:1.0
    env_file:
      - .env
    volumes:
      - .:/guardepi
    ports:
      - 5002:5002
    restart: unless-stopped
    command: "python -m app"
