services:
  guardepi:
    build:
      context: .
    image: guardepi:1.0
    env_file:
      - .env
    volumes:
      - .:/guardepi
    ports:
      - 5002:5002

    command: "poetry run python -m app"
