name: Deploy GuardEPI to Production
on:
  release:
    types: [published]

jobs:
  deploy_PRD:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/guardepi:latest
      DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
      CLOUDFLARED_TOKEN: ${{ secrets.CLOUDFLARED_TOKEN }}

    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Login to GCP
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # build image
      - name: Build Docker image
        run: docker buildx build --build-arg DOTENV_KEY=$DOTENV_KEY --build-arg CLOUDFLARED_TOKEN=$CLOUDFLARED_TOKEN -t guardepi:latest .

      # push image to registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      # deploy image
      - name: Deploy Docker image
        run: gcloud run deploy guardepi_app --image $IMAGE_NAME --region southamerica-east1 --cpu=2 --memory 1024Mi --port 5002 --min-instances 0 --max-instances 1 --platform managed --allow-unauthenticated
